# Generated by Django 5.0.2 on 2024-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(max_length=100),
        ),
    ]
